site_name: UFHCC Biostatistics and Computational Biology Shared Resource
site_description: Resources, guides, and documentation for the UFHCC BCBSR
docs_dir: docs

theme:
  name: material
  logo: assets/images/icon.png
  favicon: assets/images/icon.png
  palette:
    primary: black
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy
  font:
    text: Roboto

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/css/custom.css

extra:
  generator: false

nav:
  - Home: index.md
  - Collaborating With Us:
    - Who We Are: collaborating/who-we-are.md
    - How to Work With Us: collaborating/how-to-work-with-us.md
  - HiPerGator:
    - Intro Guide: hipergator/hipergator-intro-guide.md
    - File Naming Conventions: hipergator/file-naming-conventions.md
    - HiPerGator Example: hipergator/hipergator-example.md
  - Git & GitHub:
    - Git Collaboration: git-github/git-collaboration.md
    - Git Tips: git-github/git-tips.md
    - GitHub Actions: git-github/github-actions.md
    - GitHub CLI & Project Management: git-github/github-cli-proj-management.md
    - RStudio Git Integration: git-github/rstudio-git-integration.md
  - Command Line:
    - SSH: command-line/ssh.md
    - File Compression: command-line/file-compression.md
  - R & Python:
    - R Resources: r-python/r-resources.md
    - Lab Coding Guidelines: r-python/lab-coding-guidelines.md
    - Lab Code Style Guide: r-python/lab-code-style-guide.md
    - Parallelization in R: r-python/parallelization-R.md
    - Python Package Documentation: r-python/python-package-documentation.md
    - Software Testing in R: r-python/software-testing-R.md
  - Workflow Managers:
    - Workflow Management: workflow-managers/workflow-management.md
  - Experimental Design:
    - RNA-seq: experimental-design/RNA-seq.md
    - ATAC-seq: experimental-design/ATAC-seq.md
    - scRNA-seq: experimental-design/scRNA-seq.md
  - Analysis Pipelines:
    - RNA-seq: analysis-pipelines/RNA-seq.md
    - ATAC-seq: analysis-pipelines/ATAC-seq.md
    - scRNA-seq: analysis-pipelines/scRNA-seq.md
    - CRISPR Screen: analysis-pipelines/CRISPR-Screen.md
    - CUT&RUN: analysis-pipelines/cut-and-run.md
    - Spatial Visium: analysis-pipelines/spatial-visium-v2.md
  - Downstream Analysis:
    - Pathway Enrichment: downstream-analysis/pathway-enrichment.md
  - Data Sharing:
    - Globus: data-sharing/globus.md
    - Rclone: data-sharing/rclone.md
  - Grant Writing:
    - Bioinformatics Plan: grant-writing/bioinfo-plan.md
    - DMSP: grant-writing/DMSP.md
    - Key Personnel: grant-writing/key-personnel.md
    - Publication Figures: grant-writing/publication-figures.md
  - Publishing:
    - Authorship: publishing/authorship.md
    - Code Availability: publishing/code-availability.md
    - Data Availability: publishing/data-availability.md
    - Publication Figures: publishing/publication-figures.md
  - Blog:
    - Bioinformatics Blogs: blog/bioinfo-blogs.md
    - Journal Club: blog/journal-club.md
    - Discussion Questions: blog/discussion-questions.md

copyright: >
  © 2026 UF Health Cancer Institute Biostatistics and Computational Biology Shared Resource
