site_name: UFHCC Biostatistics and Computational Biology Shared Resource
site_description: Resources, guides, and documentation for the UFHCC BCBSR
docs_dir: docs

theme:
  name: material
  logo: assets/images/icon.png
  favicon: assets/images/icon.png
  palette:
    primary: black
  features:
    - navigation.sections
    - toc.integrate
    - content.code.copy
  font:
    text: Roboto

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/css/custom.css

extra:
  generator: false

nav:
  - Home: index.md
  - Collaborating With Us:
    - Who We Are: 01_collaborating-with-us/who-we-are.md
    - How to Work With Us: 01_collaborating-with-us/how-to-work-with-us.md
  - HiPerGator:
    - Intro Guide: 02_hipergator/hipergator-intro-guide.md
    - File Naming Conventions: 02_hipergator/file-naming-conventions.md
    - HiPerGator Example: 02_hipergator/hipergator-example.md
  - Git & GitHub:
    - Git Collaboration: 03_git-github/git-collaboration.md
    - Git Tips: 03_git-github/git-tips.md
    - GitHub Actions: 03_git-github/github-actions.md
    - GitHub CLI & Project Management: 03_git-github/github-cli-proj-management.md
    - RStudio Git Integration: 03_git-github/rstudio-git-integration.md
  - Command Line:
    - SSH: 04_command-line/ssh.md
    - File Compression: 04_command-line/file-compression.md
  - R & Python:
    - R Resources: 05_r-python/r-resources.md
    - Lab Coding Guidelines: 05_r-python/lab-coding-guidelines.md
    - Lab Code Style Guide: 05_r-python/lab-code-style-guide.md
    - Parallelization in R: 05_r-python/parallelization-R.md
    - Python Package Documentation: 05_r-python/python-package-documentation.md
    - Software Testing in R: 05_r-python/software-testing-R.md
  - Workflow Managers:
    - Workflow Management: 06_workflow-managers/workflow-management.md
  - Experimental Design:
    - RNA-seq: 09_experimental-design/RNA-seq.md
    - ATAC-seq: 09_experimental-design/ATAC-seq.md
    - scRNA-seq: 09_experimental-design/scRNA-seq.md
  - Analysis Pipelines:
    - RNA-seq: 10_analysis-pipelines/RNA-seq.md
    - ATAC-seq: 10_analysis-pipelines/ATAC-seq.md
    - scRNA-seq: 10_analysis-pipelines/scRNA-seq.md
    - CRISPR Screen: 10_analysis-pipelines/CRISPR-Screen.md
    - CUT&RUN: 10_analysis-pipelines/cut-and-run.md
    - Spatial Visium: 10_analysis-pipelines/spatial-visium-v2.md
  - Downstream Analysis:
    - Pathway Enrichment: 11_downstream-analysis/pathway-enrichment.md
  - Data Sharing:
    - Globus: 13_data-sharing/globus.md
    - Rclone: 13_data-sharing/rclone.md
  - Grant Writing:
    - Bioinformatics Plan: 14_grant-writing/bioinfo-plan.md
    - DMSP: 14_grant-writing/DMSP.md
    - Key Personnel: 14_grant-writing/key-personnel.md
    - Publication Figures: 14_grant-writing/publication-figures.md
  - Publishing:
    - Authorship: 15_publishing/authorship.md
    - Code Availability: 15_publishing/code-availability.md
    - Data Availability: 15_publishing/data-availability.md
    - Publication Figures: 15_publishing/publication-figures.md
  - Blog:
    - Bioinformatics Blogs: 19_blog/bioinfo-blogs.md
    - Journal Club: 19_blog/journal-club.md
    - Discussion Questions: 19_blog/discussion-questions.md

copyright: >
  © 2026 UF Health Cancer Institute Biostatistics and Computational Biology Shared Resource
